### PR TITLE
Blog app - controllers specs

### PR DESCRIPTION
**Pull request by ngeelani48**
**In this Pull request Following requirements are added:**

- Add RSpec as a gem to the project.
- Create a Request spec file for all the controllers.
- Make sure that for each action you check:
  - If the response status was correct.
  - If a correct template was rendered.
  - If the response body includes correct placeholder text.

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @ngeelani48 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Used RSpec to generate the tests.
✔️  Used the correct format and tested all the scenarios required for posts and user controllers.


# Required Changes ♻️

- [ ] @ngeelani48 great work implementing all the tests, however, there are some tests that are failing, kindly consider checking your `spec/model/post_spec.rb`, the author id generation is not successful on line 6, check the error am getting below 
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ngeelani48** [comment]
Hello, @danmainah Thanks for the time and review. 🙌 

Kindly can you give some more details about this issue as on my side it is giving no errors, I have tried this many times.

Screenshot (98)

**Comment by danmainah** [comment]
> Hello, @danmainah Thanks for the time and review. 🙌
> 
> Kindly can you give some more details about this issue as on my side it is giving no errors, I have tried this many times.
> 
> Screenshot (98)

@ngeelani48 as shown in the screenshot below, whenever I tried to add a new post using line 6, it was not successful due to lack of author id, had you already populated your database, I also noticed you implemented the creation of the post, and user different in other tests maybe should try to change to the format you used in other tests like for comment and like models.(I spent almost 20minutes figuring out the error, to ensure l am not missing anything )
image

**Comment by ngeelani48** [comment]
Hi @danmainah thanks for giving that much time. ❤️ 

I have tried some changes. If you can have a look at it and see if still showing issues on your side.

**Comment by danmainah** [comment]
> Hi @danmainah thanks for giving that much time. ❤️
> 
> I have tried some changes. If you can have a look at it and see if still showing issues on your side.

@ngeelani48 let me reclone it and run it again then give you the feedback.

**Comment by danmainah** [comment]
@ngeelani48 All the tests are passing now 
image

**Comment by ngeelani48** [comment]
@danmainah Thanks a lot 💯

**Comment by danmainah** [comment]
> @danmainah Thanks a lot 💯

@ngeelani48 welcome, always a pleasure to help

**Review by danmainah — APPROVED** [review]
Hi @ngeelani48 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Used RSpec to generate the tests ad ensure all tests are passing.
✔️ Used the correct format and tested all the scenarios required for posts and user controllers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
